services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_PASSWORD: mysecretpassword
  #     POSTGRES_DB: kozy
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - kozy-net
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 10

  mysql:
    image: mysql:latest
    container_name: mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: kozy
    env_file:
      - ./mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kozy-net
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: kozy-backend
    ports:
      - "5050:5050"
    volumes:
      - logs:/app/logs
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - kozy-net

  frontend:
    build: ./frontend
    container_name: kozy-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - kozy-net
    depends_on:
      - backend

networks:
  kozy-net:
    name: kozy-net
    driver: bridge
    external: true

volumes:
  logs:
  mysql_data:
    driver: local
